#!/bin/bash

# Back up all libvirt qemu / qcow2 guests.

images_dir=/var/lib/libvirt/images
backup_dir=/backups/libvirt

all_guest_fullpaths=$(sudo find "${images_dir}" -maxdepth 1 -mindepth 1 -type f)
active_guests=$(sudo virsh list | sed '1,2d;$d')

if [[ -n "$active_guests" ]]; then
  echo 'Some guests are still running. All guests must be stopped to run this script.'
  exit 0
fi

for fullpath in "${all_guest_fullpaths[@]}"; do
  guest=$(basename "${fullpath//.qcow2}")

  if [[ ! -d "${backup_dir}/${guest}" ]] || [[ ! -w "${backup_dir}/${guest}" ]]; then
    mkdir "${backup_dir}/${guest}"
  fi

  sudo virsh dumpxml "${guest}" > "${backup_dir}/${guest}/${guest}.xml" || \
    { echo "sudo virsh dumpxml ${guest} failed."; exit 1; }

  sudo cp "${fullpath}" "${backup_dir}/${guest}/${guest}.qcow2" || \
    { echo "sudo cp ${fullpath} failed."; exit 1; }

done

printf "%s\n" "$(ls -l ${backup_dir}/* )"
