#!/bin/bash

. $HOME/Repos/laputa/misc_bash/libs/lib_healthcheck.sh

custom_port=XX
user=foobar
backup_server=foobar

# Capturing a string value in addition to the return code can be useful;
# in this case it contains error messages.
result=$(pingable ${backup_server})

if [ $? = 0 ] && [ -z "$result" ]; then
  # Copy Dropbox dir to backup server.
  rsync --delete -e "ssh -p ${custom_port}" -a /home/<me>/Dropbox ${user}@${backup_server}:/backups/funnel

  # If rsync was successful, update timestamp on remote copy.
  if [ $? = 0 ]; then
    ssh -p ${custom_port} ${user}@${backup_server} touch /backups/funnel/Dropbox
  else
    printf "Something went wrong with the backup.\n"
    exit 1
  fi
else
  printf "pingable returned an error: $result.\n"
  exit 1
fi

